/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HistoricoRouteImport } from './routes/historico'
import { Route as ClassificacaoRouteImport } from './routes/classificacao'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoricoSearchIdRouteImport } from './routes/historico.$searchId'

const HistoricoRoute = HistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassificacaoRoute = ClassificacaoRouteImport.update({
  id: '/classificacao',
  path: '/classificacao',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricoSearchIdRoute = HistoricoSearchIdRouteImport.update({
  id: '/$searchId',
  path: '/$searchId',
  getParentRoute: () => HistoricoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/classificacao': typeof ClassificacaoRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/historico/$searchId': typeof HistoricoSearchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/classificacao': typeof ClassificacaoRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/historico/$searchId': typeof HistoricoSearchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/classificacao': typeof ClassificacaoRoute
  '/historico': typeof HistoricoRouteWithChildren
  '/historico/$searchId': typeof HistoricoSearchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/classificacao'
    | '/historico'
    | '/historico/$searchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/classificacao'
    | '/historico'
    | '/historico/$searchId'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/classificacao'
    | '/historico'
    | '/historico/$searchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ClassificacaoRoute: typeof ClassificacaoRoute
  HistoricoRoute: typeof HistoricoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/historico': {
      id: '/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof HistoricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classificacao': {
      id: '/classificacao'
      path: '/classificacao'
      fullPath: '/classificacao'
      preLoaderRoute: typeof ClassificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historico/$searchId': {
      id: '/historico/$searchId'
      path: '/$searchId'
      fullPath: '/historico/$searchId'
      preLoaderRoute: typeof HistoricoSearchIdRouteImport
      parentRoute: typeof HistoricoRoute
    }
  }
}

interface HistoricoRouteChildren {
  HistoricoSearchIdRoute: typeof HistoricoSearchIdRoute
}

const HistoricoRouteChildren: HistoricoRouteChildren = {
  HistoricoSearchIdRoute: HistoricoSearchIdRoute,
}

const HistoricoRouteWithChildren = HistoricoRoute._addFileChildren(
  HistoricoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ClassificacaoRoute: ClassificacaoRoute,
  HistoricoRoute: HistoricoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
